# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QGraphicsView


class MyGraphicsView(QGraphicsView):
    cnt_calls_resizeEvent = 0
    cnt_zoom = 0

    def __init__(self, parent):
        super().__init__(parent)
        self.cnt_calls_resizeEvent = 0
        self.cnt_zoom = 0

    def wheelEvent(self, event: QtGui.QWheelEvent) -> None:
        self.setTransformationAnchor(QGraphicsView.ViewportAnchor.AnchorUnderMouse)
        scale_factor = 1.5

        if event.angleDelta().y() > 0:
            self.scale(scale_factor, scale_factor)
            self.cnt_zoom += 1
        elif self.cnt_zoom != 0:
            self.scale(1 / scale_factor, 1 / scale_factor)
            self.cnt_zoom -= 1


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(927, 775)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMaximumSize(QtCore.QSize(300, 167000))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.felay_label = QtWidgets.QLabel(self.groupBox)
        self.felay_label.setObjectName("felay_label")
        self.gridLayout.addWidget(self.felay_label, 0, 0, 1, 4)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 4)
        self.points_tableWidget = QtWidgets.QTableWidget(self.groupBox)
        self.points_tableWidget.setObjectName("points_tableWidget")
        self.points_tableWidget.setColumnCount(0)
        self.points_tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.points_tableWidget, 3, 0, 1, 4)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 4)
        self.x_label = QtWidgets.QLabel(self.groupBox)
        self.x_label.setObjectName("x_label")
        self.gridLayout.addWidget(self.x_label, 5, 0, 1, 1)
        self.x_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.x_lineEdit.setObjectName("x_lineEdit")
        self.gridLayout.addWidget(self.x_lineEdit, 5, 1, 1, 3)
        self.y_label = QtWidgets.QLabel(self.groupBox)
        self.y_label.setObjectName("y_label")
        self.gridLayout.addWidget(self.y_label, 6, 0, 1, 1)
        self.y_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.y_lineEdit.setObjectName("y_lineEdit")
        self.gridLayout.addWidget(self.y_lineEdit, 6, 1, 1, 3)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 7, 0, 1, 4)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 8, 0, 1, 4)
        self.seed_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.seed_pushButton.setObjectName("seed_pushButton")
        self.gridLayout.addWidget(self.seed_pushButton, 9, 0, 1, 4)
        self.color_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.color_pushButton.setObjectName("color_pushButton")
        self.gridLayout.addWidget(self.color_pushButton, 10, 0, 1, 4)
        self.color_label = QtWidgets.QLabel(self.groupBox)
        self.color_label.setText("")
        self.color_label.setObjectName("color_label")
        self.gridLayout.addWidget(self.color_label, 11, 0, 1, 4)
        self.time_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.time_pushButton.setObjectName("time_pushButton")
        self.gridLayout.addWidget(self.time_pushButton, 12, 0, 1, 4)
        self.time_label = QtWidgets.QLabel(self.groupBox)
        self.time_label.setObjectName("time_label")
        self.gridLayout.addWidget(self.time_label, 13, 0, 1, 2)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setText("")
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 13, 2, 1, 2)
        self.dekay_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.dekay_pushButton.setObjectName("delay_pushButton")
        self.gridLayout.addWidget(self.dekay_pushButton, 1, 0, 1, 2)
        self.without_delay_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.without_delay_pushButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.without_delay_pushButton.setObjectName("without_delay_pushButton")
        self.gridLayout.addWidget(self.without_delay_pushButton, 1, 2, 1, 2)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.graphicsView = MyGraphicsView(self.centralwidget)
        self.graphicsView.setMaximumSize(QtCore.QSize(1677000, 1677000))
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_2.addWidget(self.graphicsView, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 927, 26))
        self.menubar.setObjectName("menubar")
        self.program_menu = QtWidgets.QMenu(self.menubar)
        self.program_menu.setObjectName("program_menu")
        self.author_menu = QtWidgets.QMenu(self.menubar)
        self.author_menu.setObjectName("author_menu")
        self.clear_menu = QtWidgets.QMenu(self.menubar)
        self.clear_menu.setObjectName("clear_menu")
        self.exit_menu = QtWidgets.QMenu(self.menubar)
        self.exit_menu.setObjectName("exit_menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.program_menu.menuAction())
        self.menubar.addAction(self.author_menu.menuAction())
        self.menubar.addAction(self.clear_menu.menuAction())
        self.menubar.addAction(self.exit_menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.felay_label.setText(_translate("MainWindow", "Выбор режима выполнения"))
        self.label.setText(_translate("MainWindow", "Введенные точки и ребра"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Добавление произвольной кривой - </p><p align=\"center\">Shift+зажать ЛКМ</p></body></html>"))
        self.x_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X:</span></p></body></html>"))
        self.y_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y:</span></p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "Добавить точку"))
        self.pushButton_3.setText(_translate("MainWindow", "Замкнуть фигуру"))
        self.seed_pushButton.setText(_translate("MainWindow", "Добавить затравку"))
        self.color_pushButton.setText(_translate("MainWindow", "Выбор цвета заполнения"))
        self.time_pushButton.setText(_translate("MainWindow", "Замер времени"))
        self.time_label.setText(_translate("MainWindow", "Время построения:"))
        self.dekay_pushButton.setText(_translate("MainWindow", "С задержкой"))
        self.without_delay_pushButton.setText(_translate("MainWindow", "Без задержки"))
        self.program_menu.setTitle(_translate("MainWindow", "О программе"))
        self.author_menu.setTitle(_translate("MainWindow", "Об авторе"))
        self.clear_menu.setTitle(_translate("MainWindow", "Очистка"))
        self.exit_menu.setTitle(_translate("MainWindow", "Выход"))
